version: "3"
services:

 db:
  image: postgres:latest
  restart: unless-stopped
  container_name: database
  env_file:
   - .env

 backend:
  build: ./app
  container_name: backend
  restart: unless-stopped
  ports:
   - "8000:8000"
  env_file:
   - .env
  depends_on:
   - db
  volumes:
   - ./app:/app
  entrypoint: "bash /app/docker-entrypoint.sh"
  command: "runserver 0.0.0.0:8000"
